rem set OPTS=/DPSL_OPTIMIZE_TAILCALL /DPSL_OPTIMIZE_IN_COMPILE /DPSL_OPTIMIZE_IMMEDIATELY_POP /DPSL_OPTIMIZE_CONSTANT_CALCULATION /DPSL_OPTIMIZE_SUFFIX_INCREMENT /DPSL_OPTIMIZE_BOOL_AND /DPSL_OPTIMIZE_PARENTHESES
    set OPTS=
cl PSLc.cpp /Ox /Oy /MT /DNDEBUG %OPTS%
cl PSL.cpp /Ox /Oy /MT /DNDEBUG %OPTS%
del *.obj

