set OPTS=/Zi /Oy- /MDd /DDEBUG
set OPTS=/Ox /Oy /MT /DNDEBUG

set FLAGS=/DV7_EXE /DV7_ENABLE_BCODE /DV7_BUILD_PROFILE=0 /DMBUF_SIZE_MULTIPLIER=1.5
set FLAGS2=-DV7_DISABLE_AST_TAG_NAMES -DV7_ENABLE_GC -DV7_ENABLE_COMPACTING_GC -DDISABLE_MD5 -DV7_ENABLE__Math -DV7_ENABLE__Math__random -DV7_FORCE_STRICT_MODE 
set FLAGS3=-DV7_ENABLE__Memory__stats -DNO_LIBC  -DV7_NO_FS

REM /DV7_STACK_SIZE=8192-64 
REM /DV7_STACK_SIZE=100000 

cl /Fe:v7.exe *.c %OPTS% %FLAGS% %FLAGS2%

del *.obj
