/* This file was generated by the "svnrev" utility
 * (http://www.compuphase.com/svnrev.htm).
 * You should not modify it manually, as it may be re-generated.
 *
 * $Revision: 4733$
 * $Date: 2012-06-22$
 */

#ifndef SVNREH_H
#define SVNREV_H

#define SVN_REV		4733
#define SVN_REVSTR	"4733"
#define SVN_REVDATE	"2012-06-22"
#define SVN_REVSTAMP	20120622L
#define SVN_MODIFIED	0

#endif /* SVNREV_H */
