
/* file generated by qcc, do not modify */

typedef struct
{	int	pad[28];
	func_t	fib;
	float	x;
	float	IMMEDIATE;
	func_t	main;
	float	IMMEDIATE;
} globalvars_t;

typedef struct
{
} entvars_t;

#define PROGHEADER_CRC 5271
